#!/usr/bin/env python3

"""
02_network_analysis.py

Phase A network analysis for the R-Noel cell-death project.

INPUT
-----
Workbook generated by 01_build_common_master.py, containing:
    - "network master"
    - "adult-embryo common"

PHASE A QUESTIONS
-----------------
1. What pathways emerge from our candidate genes WITHOUT selecting
   apoptosis-related terms beforehand?

2. Do the candidate genes form a structured high-confidence STRING
   network?

3. Which genes occupy interesting topological positions?

IMPORTANT
---------
This is NOT the final gene-prioritization step.

STRING edges are functional associations:
    - not necessarily direct physical interactions
    - not directed
    - not automatically causal

The local directed mechanistic death/survival network will be built
in the next phase.

OUTPUT
------
Data/Raw/Network/
Data/Processed/Network/
Figures/Network/

Also creates a copy of the workbook with:
    Degree
    Betweenness
    PageRank
    Community
filled in.

DEPENDENCIES
------------
py -m pip install pandas openpyxl requests networkx matplotlib

RUN FROM Project/
-----------------
py .\\Scripts\\02_network_analysis.py ".\\cell death project-analysis-ready.xlsx"
"""

from __future__ import annotations

import argparse
import hashlib
import io
import json
import math
import shutil
import sys
import time
from datetime import datetime, timezone
from pathlib import Path
import re

import matplotlib.pyplot as plt
import networkx as nx
import pandas as pd
import requests
from openpyxl import load_workbook
from openpyxl.comments import Comment


# ============================================================
# Configuration
# ============================================================

MASTER_SHEET = "network master"
COMMON_SHEET = "adult-embryo common"

MOUSE_TAXON = 10090
GPROFILER_ORGANISM = "mmusculus"

GPROFILER_BASE = "https://biit.cs.ut.ee/gprofiler/api"
GPROFILER_SOURCES = [
    "GO:BP",
    "KEGG",
    "REAC",
    "WP",
]

# Pinned STRING version for reproducibility.
STRING_BASE = "https://version-12-0.string-db.org/api"

DEFAULT_REQUIRED_SCORE = 700
DEFAULT_NETWORK_TYPE = "functional"

DEFAULT_CORRECTION = "fdr"
DEFAULT_ALPHA = 0.05

CALLER_IDENTITY = "R-Noel_BIOL295_network_pipeline"

HTTP_TIMEOUT = 120
HTTP_RETRIES = 3


# ============================================================
# General helpers
# ============================================================

def clean_gene(x):
    if pd.isna(x):
        return None

    x = str(x).strip()

    if not x:
        return None

    return x.upper()


def unique_ordered(values):
    seen = set()
    output = []

    for value in values:
        if value not in seen:
            seen.add(value)
            output.append(value)

    return output


def write_json(path, obj):
    path.write_text(
        json.dumps(
            obj,
            indent=2,
            ensure_ascii=False,
            default=str,
        ),
        encoding="utf-8",
    )


def read_json(path):
    return json.loads(
        path.read_text(encoding="utf-8")
    )


def sha256_file(path):
    h = hashlib.sha256()

    with path.open("rb") as f:
        while True:
            chunk = f.read(1024 * 1024)

            if not chunk:
                break

            h.update(chunk)

    return h.hexdigest()


def gene_hash(genes):
    text = "|".join(genes)

    return hashlib.sha256(
        text.encode("utf-8")
    ).hexdigest()[:10]


def request_with_retry(
    session,
    method,
    url,
    **kwargs,
):

    last_error = None

    for attempt in range(
        1,
        HTTP_RETRIES + 1,
    ):

        try:

            response = session.request(
                method,
                url,
                timeout=HTTP_TIMEOUT,
                **kwargs,
            )

            response.raise_for_status()

            return response

        except requests.RequestException as exc:

            last_error = exc

            if attempt < HTTP_RETRIES:

                wait = 2 ** (attempt - 1)

                print(
                    f"HTTP error: {exc}"
                )

                print(
                    f"Retrying in {wait}s..."
                )

                time.sleep(wait)

    raise RuntimeError(
        f"HTTP request failed: {last_error}"
    )


# ============================================================
# Workbook input
# ============================================================

def load_gene_sets(workbook_path):

    xls = pd.ExcelFile(
        workbook_path
    )

    required = [
        MASTER_SHEET,
        COMMON_SHEET,
    ]

    missing = [
        s
        for s in required
        if s not in xls.sheet_names
    ]

    if missing:

        raise ValueError(
            "Missing sheet(s): "
            + ", ".join(missing)
        )

    master = pd.read_excel(
        workbook_path,
        sheet_name=MASTER_SHEET,
    )

    common = pd.read_excel(
        workbook_path,
        sheet_name=COMMON_SHEET,
    )

    for df in [master, common]:

        if "Gene" not in df.columns:

            raise ValueError(
                "Expected a 'Gene' column."
            )

        df["Gene"] = df[
            "Gene"
        ].map(clean_gene)

        df.dropna(
            subset=["Gene"],
            inplace=True,
        )

        df.drop_duplicates(
            "Gene",
            keep="first",
            inplace=True,
        )

        df.reset_index(
            drop=True,
            inplace=True,
        )

    # Sanity check.
    outside = (
        set(common["Gene"])
        - set(master["Gene"])
    )

    if outside:

        raise ValueError(
            "Common genes absent from master: "
            + ", ".join(sorted(outside))
        )

    return master, common


# ============================================================
# g:Profiler
# ============================================================

def get_gprofiler_versions(
    session,
    raw_dir,
):

    path = (
        raw_dir
        / "gprofiler_data_versions.json"
    )

    response = request_with_retry(
        session,
        "GET",
        (
            f"{GPROFILER_BASE}"
            "/util/data_versions/"
        ),
        params={
            "organism":
                GPROFILER_ORGANISM
        },
    )

    data = response.json()

    write_json(
        path,
        data,
    )

    return data


def run_enrichment(
    session,
    genes,
    label,
    raw_dir,
    processed_dir,
    *,
    alpha=0.05,
    correction="fdr",
    exclude_iea=False,
    background=None,
    refresh=False,
):

    h = gene_hash(genes)

    iea_tag = (
        "noIEA"
        if exclude_iea
        else "withIEA"
    )

    alpha_tag = (
        str(alpha)
        .replace(".", "p")
    )

    tag = (
        f"{label}_"
        f"{correction}_"
        f"a{alpha_tag}_"
        f"{iea_tag}_"
        f"{h}"
    )

    raw_path = (
        raw_dir
        / f"gprofiler_{tag}.json"
    )

    request_path = (
        raw_dir
        / f"gprofiler_{tag}_request.json"
    )

    payload = {

        "organism":
            GPROFILER_ORGANISM,

        "query":
            genes,

        "sources":
            GPROFILER_SOURCES,

        "user_threshold":
            alpha,

        "significance_threshold_method":
            correction,

        "ordered":
            False,

        "all_results":
            False,

        "measure_underrepresentation":
            False,

        "no_iea":
            exclude_iea,

        # Preserve intersections/evidence.
        "no_evidences":
            False,

        "domain_scope":
            "annotated",
    }

    if background is not None:

        payload["background"] = (
            background
        )

        payload["domain_scope"] = (
            "custom_annotated"
        )

    write_json(
        request_path,
        payload,
    )

    if (
        raw_path.exists()
        and not refresh
    ):

        print(
            f"Using cached "
            f"g:Profiler result: "
            f"{raw_path.name}"
        )

        raw = read_json(
            raw_path
        )

    else:

        print(
            f"Running g:Profiler: "
            f"{label}"
        )

        response = request_with_retry(
            session,
            "POST",
            (
                f"{GPROFILER_BASE}"
                "/gost/profile/"
            ),
            json=payload,
        )

        raw = response.json()

        write_json(
            raw_path,
            raw,
        )

    results = raw.get(
        "result",
        [],
    )

    df = pd.DataFrame(
        results
    )

    if df.empty:

        print(
            f"No significant terms "
            f"for {label}."
        )

        df.to_csv(
            processed_dir
            / f"enrichment_{label}.csv",
            index=False,
        )

        return df

    df.rename(
        columns={
            "p_value":
                "adjusted_p_value"
        },
        inplace=True,
    )

    df.insert(
        0,
        "query_label",
        label,
    )

    df.insert(
        1,
        "input_gene_count",
        len(genes),
    )

    df.insert(
        2,
        "background_mode",
        (
            "master_candidate_background"
            if background is not None
            else "annotated_mouse_genome"
        ),
    )

    # Convert nested JSON fields safely
    # for CSV storage.
    for col in df.columns:

        if df[col].map(
            lambda x:
                isinstance(
                    x,
                    (list, dict),
                )
        ).any():

            df[col] = df[col].map(
                lambda x:
                    json.dumps(x)
                    if isinstance(
                        x,
                        (list, dict),
                    )
                    else x
            )

    df.sort_values(
        [
            "source",
            "adjusted_p_value",
        ],
        inplace=True,
    )

    df.to_csv(
        processed_dir
        / f"enrichment_{label}.csv",
        index=False,
    )

    return df


def plot_enrichment(
    df,
    label,
    figures_dir,
    top_n=15,
):

    if (
        df.empty
        or "adjusted_p_value"
        not in df.columns
    ):
        return

    for source in (
        GPROFILER_SOURCES
    ):

        sub = df[
            df["source"] == source
        ].copy()

        if sub.empty:
            continue

        sub = sub.nsmallest(
            top_n,
            "adjusted_p_value",
        )

        sub["score"] = (
            sub[
                "adjusted_p_value"
            ].map(
                lambda p:
                    -math.log10(
                        max(
                            float(p),
                            sys.float_info.min,
                        )
                    )
            )
        )

        labels = (
            sub["name"]
            .astype(str)
            .map(
                lambda x:
                    x
                    if len(x) <= 70
                    else x[:67] + "..."
            )
        )

        height = max(
            4,
            len(sub) * 0.42 + 1.5,
        )

        plt.figure(
            figsize=(10, height)
        )

        y = range(
            len(sub)
        )

        plt.barh(
            y,
            sub["score"],
        )

        plt.yticks(
            y,
            labels,
        )

        plt.gca().invert_yaxis()

        plt.xlabel(
            "-log10(adjusted p-value)"
        )

        plt.title(
            f"{label}: "
            f"{source}"
        )

        plt.tight_layout()

        source_name = (
            source.replace(
                ":",
                "_",
            )
        )

        plt.savefig(
            figures_dir
            / (
                f"enrichment_"
                f"{label}_"
                f"{source_name}.png"
            ),
            dpi=300,
            bbox_inches="tight",
        )

        plt.close()


# ============================================================
# STRING
# ============================================================

def get_string_version(
    session,
    raw_dir,
):

    response = request_with_retry(
        session,
        "GET",
        (
            f"{STRING_BASE}"
            "/json/version"
        ),
    )

    data = response.json()

    write_json(
        raw_dir
        / "string_version.json",
        data,
    )

    return data


def map_string_ids(
    session,
    genes,
    raw_dir,
    processed_dir,
    *,
    refresh=False,
):

    h = gene_hash(
        genes
    )

    raw_path = (
        raw_dir
        / f"string_mapping_{h}.tsv"
    )

    request_path = (
        raw_dir
        / f"string_mapping_{h}_request.json"
    )

    params = {

        "identifiers":
            "\r".join(genes),

        "species":
            MOUSE_TAXON,

        "echo_query":
            1,

        "caller_identity":
            CALLER_IDENTITY,
    }

    write_json(
        request_path,
        params,
    )

    if (
        raw_path.exists()
        and not refresh
    ):

        print(
            "Using cached "
            "STRING mapping."
        )

        text = (
            raw_path.read_text(
                encoding="utf-8"
            )
        )

    else:

        print(
            "Mapping genes to "
            "STRING IDs..."
        )

        response = request_with_retry(
            session,
            "POST",
            (
                f"{STRING_BASE}"
                "/tsv/get_string_ids"
            ),
            data=params,
        )

        text = response.text

        raw_path.write_text(
            text,
            encoding="utf-8",
        )

        time.sleep(1)

    mapping = pd.read_csv(
        io.StringIO(text),
        sep="\t",
    )

    mapping[
        "queryItem"
    ] = mapping[
        "queryItem"
    ].map(clean_gene)

    # STRING normally returns one
    # best hit per submitted identifier.
    mapping = (
        mapping
        .sort_values(
            "queryIndex"
        )
        .drop_duplicates(
            "queryItem",
            keep="first",
        )
    )

    mapped = set(
        mapping["queryItem"]
    )

    unmapped = pd.DataFrame(
        {
            "Gene": [
                gene
                for gene in genes
                if gene not in mapped
            ]
        }
    )

    # Detect aliases mapping to the same
    # STRING protein.
    collisions = (
        mapping
        .groupby(
            "stringId"
        )["queryItem"]
        .agg(
            lambda x:
                ";".join(
                    sorted(set(x))
                )
        )
        .reset_index(
            name="input_genes"
        )
    )

    collisions[
        "n_input_genes"
    ] = (
        collisions[
            "input_genes"
        ].str.count(";")
        + 1
    )

    collisions = (
        collisions[
            collisions[
                "n_input_genes"
            ] > 1
        ]
    )

    mapping.to_csv(
        processed_dir
        / "string_mapping.csv",
        index=False,
    )

    unmapped.to_csv(
        processed_dir
        / "string_unmapped_genes.csv",
        index=False,
    )

    collisions.to_csv(
        processed_dir
        / "string_mapping_collisions.csv",
        index=False,
    )

    return (
        mapping,
        unmapped,
        collisions,
    )


def get_string_network(
    session,
    string_ids,
    raw_dir,
    required_score,
    network_type,
    *,
    refresh=False,
):

    h = gene_hash(
        string_ids
    )

    tag = (
        f"{network_type}_"
        f"s{required_score}_"
        f"{h}"
    )

    raw_path = (
        raw_dir
        / f"string_seed_network_{tag}.tsv"
    )

    request_path = (
        raw_dir
        / f"string_seed_network_{tag}_request.json"
    )

    params = {

        "identifiers":
            "\r".join(
                string_ids
            ),

        "species":
            MOUSE_TAXON,

        "required_score":
            required_score,

        "network_type":
            network_type,

        # Critical: Phase A contains
        # only our own candidate genes.
        "add_nodes":
            0,

        "caller_identity":
            CALLER_IDENTITY,
    }

    write_json(
        request_path,
        params,
    )

    if (
        raw_path.exists()
        and not refresh
    ):

        print(
            "Using cached "
            "STRING network."
        )

        text = (
            raw_path.read_text(
                encoding="utf-8"
            )
        )

    else:

        print(
            "Downloading STRING "
            "seed-only network..."
        )

        response = request_with_retry(
            session,
            "POST",
            (
                f"{STRING_BASE}"
                "/tsv/network"
            ),
            data=params,
        )

        text = response.text

        raw_path.write_text(
            text,
            encoding="utf-8",
        )

        time.sleep(1)

    if not text.strip():

        return pd.DataFrame()

    return pd.read_csv(
        io.StringIO(text),
        sep="\t",
    )


def get_ppi_enrichment(
    session,
    string_ids,
    raw_dir,
    processed_dir,
    required_score,
    *,
    refresh=False,
):

    h = gene_hash(
        string_ids
    )

    raw_path = (
        raw_dir
        / (
            f"string_ppi_"
            f"s{required_score}_"
            f"{h}.tsv"
        )
    )

    params = {

        "identifiers":
            "\r".join(
                string_ids
            ),

        "species":
            MOUSE_TAXON,

        "required_score":
            required_score,

        "caller_identity":
            CALLER_IDENTITY,
    }

    if (
        raw_path.exists()
        and not refresh
    ):

        text = (
            raw_path.read_text(
                encoding="utf-8"
            )
        )

    else:

        print(
            "Running STRING "
            "PPI-enrichment test..."
        )

        response = request_with_retry(
            session,
            "POST",
            (
                f"{STRING_BASE}"
                "/tsv/ppi_enrichment"
            ),
            data=params,
        )

        text = response.text

        raw_path.write_text(
            text,
            encoding="utf-8",
        )

        time.sleep(1)

    ppi = pd.read_csv(
        io.StringIO(text),
        sep="\t",
    )

    ppi.to_csv(
        processed_dir
        / "string_ppi_enrichment.csv",
        index=False,
    )

    return ppi


# ============================================================
# Graph construction
# ============================================================

def build_graph(
    mapping,
    edges,
):

    G = nx.Graph()

    # Add mapped genes first so isolates are
    # retained even when STRING reports no edge.
    for _, row in mapping.iterrows():

        G.add_node(
            row["stringId"],
            gene=row["queryItem"],
            preferredName=row[
                "preferredName"
            ],
        )

    if edges.empty:

        return G

    for _, row in edges.iterrows():

        a = row[
            "stringId_A"
        ]

        b = row[
            "stringId_B"
        ]

        if a == b:
            continue

        score = float(
            row["score"]
        )

        # Confidence is a similarity/
        # strength measure.
        # Shortest-path algorithms need a
        # distance, so invert the score.
        distance = (
            1.0
            / max(score, 1e-12)
        )

        G.add_edge(
            a,
            b,
            score=score,
            distance=distance,
        )

    return G


def pagerank_power(
    G,
    alpha=0.85,
    max_iter=500,
    tol=1e-12,
):

    """
    Simple weighted PageRank power iteration.

    Avoids requiring scipy.
    """

    n = G.number_of_nodes()

    if n == 0:
        return {}

    nodes = list(G.nodes())

    rank = {
        node: 1.0 / n
        for node in nodes
    }

    strength = {
        node:
            sum(
                G[node][nbr].get(
                    "score",
                    1.0,
                )
                for nbr
                in G.neighbors(node)
            )
        for node in nodes
    }

    for _ in range(max_iter):

        new_rank = {
            node:
                (1 - alpha) / n
            for node in nodes
        }

        dangling = sum(
            rank[node]
            for node in nodes
            if strength[node] == 0
        )

        dangling_share = (
            alpha
            * dangling
            / n
        )

        for node in nodes:

            new_rank[node] += (
                dangling_share
            )

        for node in nodes:

            if strength[node] == 0:
                continue

            for nbr in G.neighbors(
                node
            ):

                weight = (
                    G[node][nbr]
                    .get(
                        "score",
                        1.0,
                    )
                )

                new_rank[nbr] += (
                    alpha
                    * rank[node]
                    * weight
                    / strength[node]
                )

        diff = sum(
            abs(
                new_rank[node]
                - rank[node]
            )
            for node in nodes
        )

        rank = new_rank

        if diff < tol:
            break

    total = sum(
        rank.values()
    )

    return {
        node:
            value / total
        for node, value
        in rank.items()
    }


def get_communities(G):

    if G.number_of_nodes() == 0:
        return {}

    if G.number_of_edges() == 0:

        return {
            node: i + 1
            for i, node
            in enumerate(G)
        }

    communities = list(
        nx.community
        .greedy_modularity_communities(
            G,
            weight="score",
        )
    )

    communities.sort(
        key=len,
        reverse=True,
    )

    result = {}

    for cid, community in enumerate(
        communities,
        start=1,
    ):

        for node in community:
            result[node] = cid

    return result


def graph_diagnostics(G):

    n = G.number_of_nodes()

    components = (
        sorted(
            nx.connected_components(G),
            key=len,
            reverse=True,
        )
        if n
        else []
    )

    return {

        "number_of_nodes":
            n,

        "number_of_edges":
            G.number_of_edges(),

        "number_of_isolates":
            len(
                list(
                    nx.isolates(G)
                )
            ),

        "number_of_connected_components":
            len(components),

        "largest_component_size":
            (
                len(components[0])
                if components
                else 0
            ),

        "largest_component_fraction":
            (
                len(components[0]) / n
                if components and n
                else 0
            ),

        "density":
            (
                nx.density(G)
                if n > 1
                else 0
            ),

        "average_degree":
            (
                sum(
                    dict(
                        G.degree()
                    ).values()
                )
                / n
                if n
                else 0
            ),

        "component_sizes":
            [
                len(c)
                for c in components
            ],
    }


def compute_metrics(G):

    if G.number_of_nodes() == 0:

        return pd.DataFrame()

    degree = dict(
        G.degree()
    )

    weighted_degree = dict(
        G.degree(
            weight="score"
        )
    )

    degree_centrality = (
        nx.degree_centrality(G)
    )

    betweenness = (
        nx.betweenness_centrality(
            G,
            normalized=True,
            weight="distance",
        )
    )

    betweenness_unweighted = (
        nx.betweenness_centrality(
            G,
            normalized=True,
            weight=None,
        )
    )

    closeness = (
        nx.closeness_centrality(
            G,
            distance="distance",
        )
    )

    pagerank = (
        pagerank_power(G)
    )

    community = (
        get_communities(G)
    )

    components = sorted(
        nx.connected_components(G),
        key=len,
        reverse=True,
    )

    component_id = {}
    component_size = {}

    for cid, comp in enumerate(
        components,
        start=1,
    ):

        for node in comp:

            component_id[node] = (
                cid
            )

            component_size[node] = (
                len(comp)
            )

    rows = []

    for node in G.nodes():

        rows.append({

            "stringId":
                node,

            "graph_gene":
                G.nodes[node]
                .get(
                    "gene",
                    "",
                ),

            "preferredName":
                G.nodes[node]
                .get(
                    "preferredName",
                    "",
                ),

            "degree":
                degree[node],

            "weighted_degree":
                weighted_degree[node],

            "degree_centrality":
                degree_centrality[node],

            "betweenness_weighted":
                betweenness[node],

            "betweenness_unweighted":
                betweenness_unweighted[
                    node
                ],

            "closeness_weighted":
                closeness[node],

            "pagerank":
                pagerank[node],

            "community":
                community[node],

            "component_id":
                component_id[node],

            "component_size":
                component_size[node],

            "isolate":
                degree[node] == 0,
        })

    return pd.DataFrame(
        rows
    )


# ============================================================
# Process node and edge tables
# ============================================================

def annotate_edges(
    edges,
    mapping,
):

    if edges.empty:
        return edges.copy()

    id_to_gene = (
        mapping
        .drop_duplicates(
            "stringId"
        )
        .set_index(
            "stringId"
        )[
            "queryItem"
        ]
        .to_dict()
    )

    output = edges.copy()

    output.insert(
        0,
        "Gene_A",
        output[
            "stringId_A"
        ].map(
            id_to_gene
        ),
    )

    output.insert(
        1,
        "Gene_B",
        output[
            "stringId_B"
        ].map(
            id_to_gene
        ),
    )

    return output


def make_node_table(
    master,
    mapping,
    metrics,
):

    map_cols = [
        col
        for col in [
            "queryItem",
            "stringId",
            "preferredName",
            "annotation",
        ]
        if col in mapping.columns
    ]

    map_small = (
        mapping[
            map_cols
        ]
        .rename(
            columns={
                "queryItem":
                    "Gene"
            }
        )
    )

    nodes = master.copy()

    nodes = nodes.merge(
        map_small,
        on="Gene",
        how="left",
    )

    if not metrics.empty:

        metric_cols = [
            col
            for col
            in metrics.columns
            if col not in [
                "graph_gene",
                "preferredName",
            ]
        ]

        nodes = nodes.merge(
            metrics[
                metric_cols
            ],
            on="stringId",
            how="left",
        )

    nodes[
        "mapping_status"
    ] = nodes[
        "stringId"
    ].notna().map(
        {
            True: "mapped",
            False: "unmapped",
        }
    )

    return nodes


# ============================================================
# Figures
# ============================================================

def plot_network_diagnostics(
    metrics,
    diagnostics,
    figures_dir,
):

    if not metrics.empty:

        plt.figure(
            figsize=(8, 5)
        )

        plt.hist(
            metrics["degree"],
            bins="auto",
        )

        plt.xlabel(
            "Degree"
        )

        plt.ylabel(
            "Number of candidate genes"
        )

        plt.title(
            "STRING seed-only degree distribution"
        )

        plt.tight_layout()

        plt.savefig(
            figures_dir
            / "string_degree_distribution.png",
            dpi=300,
            bbox_inches="tight",
        )

        plt.close()

    sizes = diagnostics[
        "component_sizes"
    ]

    if sizes:

        plt.figure(
            figsize=(8, 5)
        )

        plt.bar(
            range(
                1,
                len(sizes) + 1,
            ),
            sizes,
        )

        plt.xlabel(
            "Connected component"
        )

        plt.ylabel(
            "Number of genes"
        )

        plt.title(
            "STRING connected-component sizes"
        )

        plt.tight_layout()

        plt.savefig(
            figures_dir
            / "string_component_sizes.png",
            dpi=300,
            bbox_inches="tight",
        )

        plt.close()


# ============================================================
# Write topology back to workbook
# ============================================================

def update_workbook(
    input_path,
    output_path,
    nodes,
    required_score,
    network_type,
):

    shutil.copy2(
        input_path,
        output_path,
    )

    wb = load_workbook(
        output_path
    )

    ws = wb[
        MASTER_SHEET
    ]

    headers = {
        str(cell.value)
        .strip()
        .lower():
            cell.column

        for cell in ws[1]

        if cell.value
        is not None
    }

    required = [
        "gene",
        "degree",
        "betweenness",
        "pagerank",
        "community",
        "network notes",
    ]

    missing = [
        h
        for h in required
        if h not in headers
    ]

    if missing:

        raise ValueError(
            "Missing workbook "
            "column(s): "
            + ", ".join(missing)
        )

    lookup = (
        nodes
        .drop_duplicates("Gene")
        .set_index("Gene")
    )

    gene_col = headers[
        "gene"
    ]

    for row in range(
        2,
        ws.max_row + 1,
    ):

        gene = clean_gene(
            ws.cell(
                row,
                gene_col,
            ).value
        )

        if (
            not gene
            or gene
            not in lookup.index
        ):
            continue

        rec = lookup.loc[
            gene
        ]

        if pd.notna(
            rec.get("degree")
        ):

            ws.cell(
                row,
                headers["degree"],
            ).value = int(
                rec["degree"]
            )

            ws.cell(
                row,
                headers["betweenness"],
            ).value = float(
                rec[
                    "betweenness_weighted"
                ]
            )

            ws.cell(
                row,
                headers["pagerank"],
            ).value = float(
                rec["pagerank"]
            )

            ws.cell(
                row,
                headers["community"],
            ).value = int(
                rec["community"]
            )

        notes = []

        if (
            rec.get(
                "mapping_status"
            )
            == "unmapped"
        ):

            notes.append(
                "STRING v12.0: unmapped"
            )

        elif bool(
            rec.get(
                "isolate",
                False,
            )
        ):

            notes.append(
                "STRING v12.0: "
                f"isolate at score >= "
                f"{required_score}"
            )

        if notes:

            ws.cell(
                row,
                headers[
                    "network notes"
                ],
            ).value = "; ".join(
                notes
            )

    method = (
        f"STRING v12.0; "
        f"Mus musculus; "
        f"{network_type}; "
        f"required_score >= "
        f"{required_score}; "
        f"add_nodes=0. "
        "Weighted betweenness uses "
        "distance = 1 / STRING score."
    )

    ws.cell(
        1,
        headers["degree"],
    ).comment = Comment(
        method,
        "R-Noel pipeline",
    )

    ws.cell(
        1,
        headers["betweenness"],
    ).comment = Comment(
        method,
        "R-Noel pipeline",
    )

    ws.cell(
        1,
        headers["pagerank"],
    ).comment = Comment(
        method,
        "R-Noel pipeline",
    )

    ws.cell(
        1,
        headers["community"],
    ).comment = Comment(
        method,
        "R-Noel pipeline",
    )

    wb.save(
        output_path
    )


# ============================================================
# Main
# ============================================================

def main():

    parser = argparse.ArgumentParser()

    parser.add_argument(
        "workbook",
        type=Path,
    )

    parser.add_argument(
        "--required-score",
        type=int,
        default=
            DEFAULT_REQUIRED_SCORE,
    )

    parser.add_argument(
        "--network-type",
        choices=[
            "functional",
            "physical",
        ],
        default=
            DEFAULT_NETWORK_TYPE,
    )

    parser.add_argument(
        "--correction",
        choices=[
            "fdr",
            "g_SCS",
            "bonferroni",
        ],
        default=
            DEFAULT_CORRECTION,
    )

    parser.add_argument(
        "--alpha",
        type=float,
        default=
            DEFAULT_ALPHA,
    )

    parser.add_argument(
        "--exclude-iea",
        action="store_true",
    )

    parser.add_argument(
        "--refresh",
        action="store_true",
    )

    parser.add_argument(
        "--top-n",
        type=int,
        default=15,
    )

    args = parser.parse_args()

    workbook = (
        args.workbook
        .expanduser()
        .resolve()
    )

    if not workbook.exists():

        raise FileNotFoundError(
            workbook
        )

    if not (
        0
        <= args.required_score
        <= 1000
    ):

        parser.error(
            "--required-score must "
            "be between 0 and 1000."
        )

    project_root = (
        Path(__file__)
        .resolve()
        .parent
        .parent
    )

    raw_dir = (
        project_root
        / "Data"
        / "Raw"
        / "Network"
    )

    processed_dir = (
        project_root
        / "Data"
        / "Processed"
        / "Network"
    )

    figures_dir = (
        project_root
        / "Figures"
        / "Network"
    )

    for directory in [
        raw_dir,
        processed_dir,
        figures_dir,
    ]:

        directory.mkdir(
            parents=True,
            exist_ok=True,
        )

    print()
    print(
        "R-Noel network analysis "
        "- Phase A"
    )
    print(
        "=========================="
    )

    master, common = (
        load_gene_sets(
            workbook
        )
    )

    master_genes = (
        unique_ordered(
            master["Gene"].tolist()
        )
    )

    common_genes = (
        unique_ordered(
            common["Gene"].tolist()
        )
    )

    print(
        "Master genes:",
        len(master_genes),
    )

    print(
        "Adult-embryo common:",
        len(common_genes),
    )

    # Save exact inputs.
    master.to_csv(
        processed_dir
        / "master_seed_genes.csv",
        index=False,
    )

    common.to_csv(
        processed_dir
        / "common_seed_genes.csv",
        index=False,
    )

    session = (
        requests.Session()
    )

    session.headers.update(
        {
            "User-Agent":
                CALLER_IDENTITY
        }
    )

    # --------------------------
    # Provenance
    # --------------------------

    metadata = {

        "run_utc":
            datetime.now(
                timezone.utc
            ).isoformat(),

        "input_workbook":
            str(workbook),

        "input_sha256":
            sha256_file(
                workbook
            ),

        "master_gene_count":
            len(master_genes),

        "common_gene_count":
            len(common_genes),

        "gprofiler_sources":
            GPROFILER_SOURCES,

        "gprofiler_correction":
            args.correction,

        "gprofiler_alpha":
            args.alpha,

        "string_version":
            "12.0",

        "string_required_score":
            args.required_score,

        "string_network_type":
            args.network_type,

        "string_add_nodes":
            0,
    }

    # --------------------------
    # Enrichment
    # --------------------------

    print()
    print(
        "Retrieving g:Profiler "
        "version metadata..."
    )

    metadata[
        "gprofiler_versions"
    ] = get_gprofiler_versions(
        session,
        raw_dir,
    )

    enrichment_master = (
        run_enrichment(
            session,
            master_genes,
            "master_genome",
            raw_dir,
            processed_dir,
            alpha=args.alpha,
            correction=
                args.correction,
            exclude_iea=
                args.exclude_iea,
            refresh=args.refresh,
        )
    )

    enrichment_common = (
        run_enrichment(
            session,
            common_genes,
            "common_genome",
            raw_dir,
            processed_dir,
            alpha=args.alpha,
            correction=
                args.correction,
            exclude_iea=
                args.exclude_iea,
            refresh=args.refresh,
        )
    )

    # Secondary question:
    # Which processes are relatively
    # enriched within the common genes
    # compared with the already selected
    # 131-gene candidate universe?
    enrichment_common_vs_master = (
        run_enrichment(
            session,
            common_genes,
            "common_vs_master",
            raw_dir,
            processed_dir,
            alpha=args.alpha,
            correction=
                args.correction,
            exclude_iea=
                args.exclude_iea,
            background=
                master_genes,
            refresh=args.refresh,
        )
    )

    for label, df in [

        (
            "master_genome",
            enrichment_master,
        ),

        (
            "common_genome",
            enrichment_common,
        ),

        (
            "common_vs_master",
            enrichment_common_vs_master,
        ),
    ]:

        plot_enrichment(
            df,
            label,
            figures_dir,
            args.top_n,
        )

    # --------------------------
    # STRING
    # --------------------------

    print()
    print(
        "Retrieving STRING "
        "version metadata..."
    )

    metadata[
        "string_version_response"
    ] = get_string_version(
        session,
        raw_dir,
    )

    mapping, unmapped, collisions = (
        map_string_ids(
            session,
            master_genes,
            raw_dir,
            processed_dir,
            refresh=args.refresh,
        )
    )

    string_ids = (
        unique_ordered(
            mapping[
                "stringId"
            ]
            .dropna()
            .astype(str)
            .tolist()
        )
    )

    edges_raw = (
        get_string_network(
            session,
            string_ids,
            raw_dir,
            args.required_score,
            args.network_type,
            refresh=args.refresh,
        )
    )

    ppi = (
        get_ppi_enrichment(
            session,
            string_ids,
            raw_dir,
            processed_dir,
            args.required_score,
            refresh=args.refresh,
        )
    )

    # --------------------------
    # Graph
    # --------------------------

    G = build_graph(
        mapping,
        edges_raw,
    )

    diag = (
        graph_diagnostics(G)
    )

    metrics = (
        compute_metrics(G)
    )

    edge_table = (
        annotate_edges(
            edges_raw,
            mapping,
        )
    )

    edge_table.to_csv(
        processed_dir
        / "string_seed_edges.csv",
        index=False,
    )

    node_table = (
        make_node_table(
            master,
            mapping,
            metrics,
        )
    )

    node_table.to_csv(
        processed_dir
        / "string_seed_node_metrics.csv",
        index=False,
    )

    write_json(
        processed_dir
        / "string_seed_diagnostics.json",
        diag,
    )

    # Adult-embryo common induced subgraph.
    common_ids = set(
        mapping[
            mapping[
                "queryItem"
            ].isin(
                common_genes
            )
        ][
            "stringId"
        ]
    )

    common_graph = (
        G.subgraph(
            common_ids
        ).copy()
    )

    write_json(
        processed_dir
        / "string_common_diagnostics.json",
        graph_diagnostics(
            common_graph
        ),
    )

    nx.write_graphml(
        G,
        processed_dir
        / "string_seed_network.graphml",
    )

    plot_network_diagnostics(
        metrics,
        diag,
        figures_dir,
    )

    # --------------------------
    # Workbook output
    # --------------------------

    output_workbook = (
        workbook.with_name(
            workbook.stem
            + "-network-phaseA.xlsx"
        )
    )

    update_workbook(
        workbook,
        output_workbook,
        node_table,
        args.required_score,
        args.network_type,
    )

    # --------------------------
    # Finish metadata
    # --------------------------

    metadata[
        "string_mapped_genes"
    ] = int(
        mapping[
            "queryItem"
        ].nunique()
    )

    metadata[
        "string_unmapped_genes"
    ] = len(
        unmapped
    )

    metadata[
        "string_mapping_collisions"
    ] = len(
        collisions
    )

    metadata[
        "network_diagnostics"
    ] = {
        k: v
        for k, v
        in diag.items()
        if k != "component_sizes"
    }

    write_json(
        processed_dir
        / "run_metadata.json",
        metadata,
    )

    # --------------------------
    # Console report
    # --------------------------

    print()
    print(
        "STRING seed-only network"
    )
    print(
        "------------------------"
    )

    print(
        "Mapped nodes:",
        diag[
            "number_of_nodes"
        ],
    )

    print(
        "Edges:",
        diag[
            "number_of_edges"
        ],
    )

    print(
        "Isolates:",
        diag[
            "number_of_isolates"
        ],
    )

    print(
        "Components:",
        diag[
            "number_of_connected_components"
        ],
    )

    print(
        "Largest component:",
        diag[
            "largest_component_size"
        ],
    )

    print(
        "Average degree:",
        round(
            diag[
                "average_degree"
            ],
            3,
        ),
    )

    if not ppi.empty:

        print()

        print(
            "STRING PPI enrichment:"
        )

        print(
            ppi.to_string(
                index=False
            )
        )

    # Show topology as a diagnostic,
    # not as a biological ranking.
    top = (
        node_table[
            node_table[
                "betweenness_weighted"
            ].notna()
        ]
        .sort_values(
            [
                "betweenness_weighted",
                "degree",
            ],
            ascending=[
                False,
                False,
            ],
        )
        .head(10)
    )

    print()
    print(
        "Highest weighted "
        "betweenness "
        "(diagnostic only)"
    )
    print(
        "-------------------------"
    )

    print(
        top[
            [
                "Gene",
                "degree",
                "betweenness_weighted",
                "pagerank",
                "community",
            ]
        ].to_string(
            index=False
        )
    )

    print()
    print(
        "Phase A complete."
    )

    print(
        "Updated workbook:",
        output_workbook,
    )

    print(
        "Processed data:",
        processed_dir,
    )

    print(
        "Figures:",
        figures_dir,
    )

    print()
    print(
        "Do NOT interpret the "
        "centrality ordering as our "
        "final gene priority list."
    )


if __name__ == "__main__":
    main()